Public Class OffertaDett
    Public Property F1SOCMDB() As String
    Public Property F1CENMDB() As String
    Public Property F1IDRIGA() As String
    Public Property F1IDOFF() As String
    Public Property F1ORD() As String
    Public Property F1CODDIZ() As String
    Public Property F1VOCSINT() As String
    Public Property F1CODVOCE() As String
    Public Property F1SOTTOVOC() As String
    Public Property F1LISTMAN() As String
    Public Property F1STVOCE() As String
    Public Property F1DESCRBRV() As String
    Public Property F1DESCR() As String
    Public Property F1UNMIS() As String
    Public Property F1VARSGN() As String
    Public Property F1VARTIPO() As String
    Public Property F1VARIAZ() As String
    Public Property F1QTA() As String
    Public Property F1TPMAGG() As String
    Public Property F1MAGGIOR() As String
    Public Property F1FLMOD() As String
    Public Property F1FLSTQTA() As String
    Public Property F1CODIVA() As String
    Public Property F1NRORE() As String
    Public Property F1COSTOMAT() As String
    Public Property F1MANODOP() As String
    Public Property F1IMPVOC() As String
    Public Property F1TOTRIGC() As String
    Public Property F1TRNVNK2() As String
    Public Property F1TRNV() As String
    Public Property F1TOTRIGA() As String
    Public Property F1IMTOTMAN() As String
    Public Property F1RISORSA() As String
    Public Property F1CODCOTT() As String
    Public Property F1NRORD() As String
    Public Property F1IDBUONO() As String
    Public Property Subappaltatore() As Fornitore
End Class
