'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LiftCore.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Account() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Account", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Aggiorna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Aggiorna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Aggiorna___Eccezione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Aggiorna___Eccezione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Allegato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Allegato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Archivio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Archivio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Azienda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Azienda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Azienda___Dipartimento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Azienda___Dipartimento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Azienda___Organizzazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Azienda___Organizzazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Calendario___Pagamento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Calendario___Pagamento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Calendario___Settimana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Calendario___Settimana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Cerca___dettaglio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Cerca___dettaglio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Cestino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Cestino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Chiudi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Chiudi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Cloud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Cloud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Commento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Commento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Comunicazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Comunicazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Comunicazione___Alternato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Comunicazione___Alternato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Diagramma_di_Venn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Diagramma_di_Venn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Diagramma_di_Venn_RGB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Diagramma_di_Venn_RGB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocAggiorna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocAggiorna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocAggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocAggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocAnnulla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocAnnulla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocAttesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocAttesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocBarcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocBarcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocBlocca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocBlocca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocCerca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocCerca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocCollega() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocCollega", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocDuplica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocDuplica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocElimina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocElimina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocFiltro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocFiltro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocImmagine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocImmagine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocLink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocLink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocModifica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocModifica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocNotizie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocNotizie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocOpzioni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocOpzioni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocOrdine_d_acquisto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocOrdine_d_acquisto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocOrdine_d_acquisto___Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocOrdine_d_acquisto___Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocPdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocPdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocPreferito() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocPreferito", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocProcesso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocProcesso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocQrCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocQrCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocSalva() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocSalva", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocScaduto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocScaduto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocScanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocScanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_DocStat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_DocStat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Euro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Euro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura___Cartella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura___Cartella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura___Cassa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura___Cassa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura___Monete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura___Monete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura___Ricevuta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura___Ricevuta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fattura___Ricevuta_Cassa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fattura___Ricevuta_Cassa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fiamma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fiamma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Firma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Firma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Fun___Stormtrooper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Fun___Stormtrooper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Garanzia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Garanzia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Grafico___Economico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Grafico___Economico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Lavori_in_Option___corso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Lavori_in_Option___corso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Lista___Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Lista___Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Lista___Controllo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Lista___Controllo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Mail____() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Mail____", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Mail___Aggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Mail___Aggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Mail___New_Message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Mail___New_Message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Mail___Rubrica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Mail___Rubrica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Mappe___Località() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Mappe___Località", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Obiettivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Obiettivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option___Ingranaggi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option___Ingranaggi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option___Ingranaggio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option___Ingranaggio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option___Manutenzione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option___Manutenzione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option___Ordinamento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option___Ordinamento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option___Strumenti_di_amministrazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option___Strumenti_di_amministrazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Option_Privacy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Option_Privacy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Promemoria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Promemoria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Promemoria___Aggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Promemoria___Aggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Riavvio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Riavvio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_RiquadroApri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_RiquadroApri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_RiquadroChiudi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_RiquadroChiudi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Scambio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Scambio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Servizio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Servizio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Spegni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Spegni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Stampante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Stampante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Uscita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Uscita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Utenti___Idea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Utenti___Idea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_Utenti___Sviluppo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_Utenti___Sviluppo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32_VideoConferenza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_VideoConferenza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Option() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Option", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Account() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Account", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aggiorna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aggiorna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aggiorna___Eccezione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aggiorna___Eccezione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Allegato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Allegato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Archivio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Archivio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Azienda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Azienda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Azienda___Dipartimento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Azienda___Dipartimento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Azienda___Organizzazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Azienda___Organizzazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendario___Pagamento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendario___Pagamento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendario___Settimana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendario___Settimana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property camera_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cerca___dettaglio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cerca___dettaglio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cestino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cestino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chiudi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chiudi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cloud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cloud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Commento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Commento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Comunicazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comunicazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Comunicazione___Alternato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comunicazione___Alternato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Contratto_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contratto_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Diagramma_di_Venn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Diagramma_di_Venn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Diagramma_di_Venn_RGB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Diagramma_di_Venn_RGB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocAggiorna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocAggiorna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocAggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocAggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocAnnulla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocAnnulla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocAttesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocAttesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocBarcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocBarcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocBlocca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocBlocca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocCerca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocCerca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocCollega() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocCollega", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocDuplica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocDuplica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocElimina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocElimina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocFiltro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocFiltro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocImmagine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocImmagine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocLink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocLink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocModifica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocModifica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocNotizie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocNotizie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocOpzioni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocOpzioni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocOrdine_d_acquisto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocOrdine_d_acquisto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocOrdine_d_acquisto___Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocOrdine_d_acquisto___Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocPdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocPdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocPreferito() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocPreferito", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocProcesso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocProcesso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocQrCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocQrCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocSalva() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocSalva", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocScaduto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocScaduto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocScanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocScanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocStat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocStat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Euro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Euro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura___Cartella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura___Cartella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura___Cassa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura___Cassa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura___Monete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura___Monete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura___Ricevuta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura___Ricevuta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fattura___Ricevuta_Cassa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fattura___Ricevuta_Cassa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fiamma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fiamma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_group_line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_group_line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Firma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Firma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fun___Stormtrooper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fun___Stormtrooper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Garanzia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Garanzia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grafico___Economico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grafico___Economico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconXls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconXls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lavori_in_Option___corso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lavori_in_Option___corso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lista___Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lista___Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lista___Controllo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lista___Controllo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail____() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail____", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail___Aggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail___Aggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail___New_Message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail___New_Message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail___Rubrica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail___Rubrica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mappe___Località() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mappe___Località", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Modifica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modifica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obiettivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obiettivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Offerta_Accettata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offerta_Accettata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Offerta_Al_vaglio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offerta_Al_vaglio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Offerta_Annullata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offerta_Annullata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Offerta_Bloccata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offerta_Bloccata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option___Ingranaggi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option___Ingranaggi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option___Ingranaggio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option___Ingranaggio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option___Manutenzione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option___Manutenzione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option___Ordinamento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option___Ordinamento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option___Strumenti_di_amministrazione() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option___Strumenti_di_amministrazione", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Option_Privacy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Option_Privacy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Promemoria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Promemoria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Promemoria___Aggiungi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Promemoria___Aggiungi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Riavvio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Riavvio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rimuovi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rimuovi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RiquadroApri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RiquadroApri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RiquadroChiudi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RiquadroChiudi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scambio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scambio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Servizio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Servizio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spegni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spegni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stampante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stampante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Su() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Su", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uscita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uscita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Utenti___Idea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Utenti___Idea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Utenti___Sviluppo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Utenti___Sviluppo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VideoConferenza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VideoConferenza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
