Public Class OffertaDett
    Public Property STATUS() As String
    Public Property F1SOCMDB() As String
    Public Property F1CENMDB() As String
    Public Property F1IDRIGA() As Integer
    Public Property F1IDOFF() As Integer
    Public Property F1ORD() As Integer
    Public Property F1CODDIZ() As String
    Public Property F1VOCSINT() As Integer
    Public Property F1CODVOCE() As Integer
    Public Property F1SOTTOVOC() As Integer
    Public Property F1LISTMAN() As String
    Public Property F1STVOCE() As String
    Public Property F1DESCRBRV() As String
    Public Property F1DESCR() As String
    Public Property F1UNMIS() As String
    Public Property F1VARSGN() As String
    Public Property F1VARTIPO() As String
    Public Property F1VARIAZ() As Double
    Public Property F1QTA() As Integer
    Public Property F1TPMAGG() As String
    Public Property F1MAGGIOR() As Integer
    Public Property F1FLMOD() As Single
    Public Property F1FLSTQTA() As Single
    Public Property F1CODIVA() As String
    Public Property F1NRORE() As Double
    Public Property F1COSTOMAT() As Double
    Public Property F1MANODOP() As Double
    Public Property F1IMPVOC() As Double
    Public Property F1TOTRIGC() As Double
    Public Property F1TRNVNK2() As Double
    Public Property F1TRNV() As Double
    Public Property F1TOTRIGA() As Double
    Public Property F1IMTOTMAN() As Double
    Public Property F1RISORSA() As String
    Public Property F1CODCOTT() As String
    Public Property F1NRORD() As String
    Public Property F1IDBUONO() As Integer
    Public Property DOIMMAG() As String
    Public Property DOIMMALIGN() As String
    Public Property DOIMMBORD() As String
    Public Property DOIMMBORDSTY() As String
    Public Property Subappaltatore() As Fornitore
    Public Property Operazione() As Char
End Class
